name: run-github-stats-checkpoint

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PGPASSWORD: password

jobs:
  great_expectations_validation:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: data_quality
          POSTGRES_USER: huy
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install python
        uses: actions/setup-python@v3

      - name: Copy Repository contents
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci

      - name: Connect to PostgreSQL
        run: psql -h localhost -p 5432 -U huy -d data_quality -c "SELECT * FROM app.customer;"

      - name: Run Checkpoint
        run: |
          python great_expectations/checkpoints/run_customer.py
