name: Connect to local PostgreSQL database

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PGPASSWORD: password

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

    env:
      POSTGRES_USER: huy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_quality
    ports:
      - '5432:5432'
    steps:
      - uses: actions/checkout@v2
      - name: Connect to local PostgreSQL database
        run: |
          psql -h localhost -p 5432 -U huy -d data_quality "\dn"
