name: run_GE_checkpoints

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PGPASSWORD: password

jobs:
  great_expectations_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Install python
        uses: actions/setup-python@v3

      - name: Copy Repository contents
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Connect to PostgreSQL
        run: |
          psql -h http://127.0.0.1 -p 5432 -U user -d ge_db -c "\dn"

      - name: Run Checkpoint
        run: |
          python great_expectations/checkpoints/run_customer.py
